apiVersion: v1
kind: Secret
metadata:
  name: logfilter-secrets
  namespace: logfilter
type: Opaque
stringData:
  LOGFILTER_ADMIN_TOKEN: "REPLACE-ME"
  LOGFILTER_API_TOKEN: "REPLACE-ME"
  LOGFILTER_METRICS_TOKEN: ""
  ES_PASSWORD: "REPLACE-ME"
  KAFKA_SASL_USERNAME: ""
  KAFKA_SASL_PASSWORD: ""
  KAFKA_SSL_PASSWORD: ""
  HF_TOKEN: ""
